id: I686BB9F4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T17:07:08+00:00'
last_modified: '2022-06-07T12:34:05.890682+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS18094
  title: ལོ་མ་གྱོན་མར་བརྟེན་པའི་རིལ་སྒྲུབ་ཀྱི་ངག་འདོན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    7F37:
      image_group_id: I8LS18132
      title: ''
      total_pages: 18
      order: 1
      base_file: 7F37.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
