id: P000655
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-16 15:57:31.852083
source_metadata:
  id: bdr:W8LS18094
  title: ལོ་མ་གྱོན་མར་བརྟེན་པའི་རིལ་སྒྲུབ་ཀྱི་ངག་འདོན།
  author: ''
  volumes:
    3f85f8e8573348d7aa0e919982689c8d:
      image_group_id: I8LS18132
      title: ''
      volume_number: 1
      total_pages: 18
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
